# Generated by Django 3.1.7 on 2021-03-01 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, unique=True)),
                ('last_name', models.CharField(max_length=32, unique=True)),
                ('emailid', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('up', models.CharField(max_length=32, unique=True)),
                ('up2', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(default='name', max_length=300, unique=True)),
                ('number', models.CharField(default='9999999999', max_length=300, unique=True)),
                ('comments', models.CharField(default='Enter comments', max_length=300)),
            ],
        ),
    ]
